name: CI/CD Process
on:
  workflow_call:
  workflow_dispatch:
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu, macos]
    runs-on: ${{ matrix.os }}-latest
    steps:
      - name: Checkout
        uses: DanySK/action-checkout@0.2.22
      - uses: actions/setup-python@v5
        with:
            python-version: '3.10'
            cache: 'pip'
      - name: Install dependencies
        run: pip install -r requirements.txt
  format:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Checkout
        uses: DanySK/action-checkout@0.2.22
      - uses: actions/setup-python@v5
        with:
            python-version: '3.10'
            cache: 'pip'
      - name: Install dependencies
        run: pip install isort "black[jupyter]" flake8
      - name: Check code with isort
        run: isort --check .
      - name: Check code with black
        run: black --check .
      - name: Check code with flake8
        run: flake8 **/*.py

  success:
    runs-on: ubuntu-latest
    needs:
      - build
      - format
    if: >-
      always() && (
        contains(join(needs.*.result, ','), 'failure')
        || !contains(join(needs.*.result, ','), 'cancelled')
      )
    steps:
      - name: Verify that there were no failures
        run: ${{ !contains(join(needs.*.result, ','), 'failure') }}

